testing_mode = false
payment_provider = "stripe"
stripe_api_key_test = "pk_live_51PqzkERouFeroleDqYnqZClemZ1EOfHT6DCWhTZfIBd6nDbjj2FbfPuUwEphmfOcMZep4sMdcgAUumybpohPi2iR00Qzoqkgfo"
stripe_api_key = "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"
stripe_link = "https://buy.stripe.com/4gwbLOa63bAwg6ccMM"
stripe_link_test = "https://buy.stripe.com/test_..."
client_id = "405134594415-8e9fjjuddl1r8lnr6sutbddjcgufl3ft.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = "contestsim-m5htxcxuq9tdwvjtqk3sww.streamlit.app"
redirect_url = "contestsim-m5htxcxuq9tdwvjtqk3sww.streamlit.app"
bmac_api_key = "ey..."
bmac_link = "https://www.buymeacoffee.com/..."
