testing_mode = false
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "pk_live_51Prso7KxCoXwUhAnHDBy5BLi0rY1mT8UihM8laMDD2WHzZaAyOwfzEWR7ZIffgQVouHYzKnWHj3RPL74UHX3YmsL00d1VSctrA" #only needed if using Stripe
stripe_api_key = "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" #only needed if using Stripe
stripe_link = "https://buy.stripe.com/4gweXOgio0w2e1W3cc" #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/4gweXOgio0w2e1W3cc" #only needed if using Stripe
client_id = "462658090161-afjc8eo6uothhed5v8dmuapj2t3pt827.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'https://contestsim-filebpe8yh76xqhzwv5yvr.streamlit.app/'
redirect_url = "https://contestsim-filebpe8yh76xqhzwv5yvr.streamlit.app/"
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee
