[payments]
STRIPE_PUBLISHABLE_KEY = "pk_live_51PqzkERouFeroleDqYnqZClemZ1EOfHT6DCWhTZfIBd6nDbjj2FbfPuUwEphmfOcMZep4sMdcgAUumybpohPi2iR00Qzoqkgfo"
STRIPE_SECRET_KEY = "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"
STRIPE_PRICE_ID = "price_1Pr004RouFeroleDRDHOdJAb"
